name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print repository value
      run: 
           echo "${{ github.repository "}}
           echo "${{ github.repository "}}
           echo "${{ github.repository "}}
           echo "${{ github.repository "}}
           echo "${{ github.repository "}}
           echo "${{ github.repository "}}
